sample-flask | 20:53:37 [2021-03-29 00:53:37 +0000] [1] [INFO] Starting gunicorn 20.0.4
sample-flask | 20:53:37 [2021-03-29 00:53:37 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
sample-flask | 20:53:37 [2021-03-29 00:53:37 +0000] [1] [INFO] Using worker: sync
sample-flask | 20:53:37 [2021-03-29 00:53:37 +0000] [17] [INFO] Booting worker with pid: 17
sample-flask | 20:53:37 [2021-03-29 00:53:37 +0000] [17] [ERROR] Exception in worker process
sample-flask | 20:53:37 Traceback (most recent call last):
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
sample-flask | 20:53:37     worker.init_process()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
sample-flask | 20:53:37     self.load_wsgi()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
sample-flask | 20:53:37     self.wsgi = self.app.wsgi()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
sample-flask | 20:53:37     self.callable = self.load()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
sample-flask | 20:53:37     return self.load_wsgiapp()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
sample-flask | 20:53:37     return util.import_app(self.app_uri)
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
sample-flask | 20:53:37     mod = importlib.import_module(module)
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
sample-flask | 20:53:37     return _bootstrap._gcd_import(name[level:], package, level)
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
sample-flask | 20:53:37   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
sample-flask | 20:53:37   File "/workspace/app.py", line 1, in <module>
sample-flask | 20:53:37     import stripe
sample-flask | 20:53:37 ModuleNotFoundError: No module named 'stripe'
sample-flask | 20:53:37 [2021-03-29 00:53:37 +0000] [17] [INFO] Worker exiting (pid: 17)
sample-flask | 20:53:37 [2021-03-29 00:53:37 +0000] [18] [INFO] Booting worker with pid: 18
sample-flask | 20:53:37 [2021-03-29 00:53:37 +0000] [18] [ERROR] Exception in worker process
sample-flask | 20:53:37 Traceback (most recent call last):
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
sample-flask | 20:53:37     worker.init_process()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
sample-flask | 20:53:37     self.load_wsgi()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
sample-flask | 20:53:37     self.wsgi = self.app.wsgi()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
sample-flask | 20:53:37     self.callable = self.load()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
sample-flask | 20:53:37     return self.load_wsgiapp()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
sample-flask | 20:53:37     return util.import_app(self.app_uri)
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
sample-flask | 20:53:37     mod = importlib.import_module(module)
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
sample-flask | 20:53:37     return _bootstrap._gcd_import(name[level:], package, level)
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
sample-flask | 20:53:37   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
sample-flask | 20:53:37   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
sample-flask | 20:53:37   File "/workspace/app.py", line 1, in <module>
sample-flask | 20:53:37     import stripe
sample-flask | 20:53:37 ModuleNotFoundError: No module named 'stripe'
sample-flask | 20:53:37 [2021-03-29 00:53:37 +0000] [18] [INFO] Worker exiting (pid: 18)
sample-flask | 20:53:37 Traceback (most recent call last):
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 202, in run
sample-flask | 20:53:37     self.manage_workers()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
sample-flask | 20:53:37     self.spawn_workers()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
sample-flask | 20:53:37     time.sleep(0.1 * random.random())
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
sample-flask | 20:53:37     self.reap_workers()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
sample-flask | 20:53:37     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
sample-flask | 20:53:37 gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
sample-flask | 20:53:37 
sample-flask | 20:53:37 During handling of the above exception, another exception occurred:
sample-flask | 20:53:37 
sample-flask | 20:53:37 Traceback (most recent call last):
sample-flask | 20:53:37   File "/workspace/.heroku/python/bin/gunicorn", line 8, in <module>
sample-flask | 20:53:37     sys.exit(run())
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
sample-flask | 20:53:37     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 228, in run
sample-flask | 20:53:37     super().run()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
sample-flask | 20:53:37     Arbiter(self).run()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
sample-flask | 20:53:37     self.halt(reason=inst.reason, exit_status=inst.exit_status)
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
sample-flask | 20:53:37     self.stop()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
sample-flask | 20:53:37     time.sleep(0.1)
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
sample-flask | 20:53:37     self.reap_workers()
sample-flask | 20:53:37   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
sample-flask | 20:53:37     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
sample-flask | 20:53:37 gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
